{"name": "Id заказа не задан", "status": "passed", "description": "Прием заказа без ID заказа. В описании ошибка должна быть 400 Недостаточно данных для поиска, на самом деле возвращает 404 Not Found, но в задании проверить, что вернет ошибку", "steps": [{"name": "принятие заказа ", "status": "passed", "start": 1726947212752, "stop": 1726947212889}, {"name": "Ожидаемый ответ 404, фактический 404", "status": "passed", "start": 1726947212889, "stop": 1726947212889}, {"name": "Ожидаемый json {'code': 404, 'message': 'Not Found.'}, фактический {'code': 404, 'message': 'Not Found.'}", "status": "passed", "start": 1726947212889, "stop": 1726947212889}], "start": 1726947212752, "stop": 1726947212890, "uuid": "bcbdf8f9-56cc-47e7-b279-5538feebffe7", "historyId": "9fb8bb79cc24c81216abb8d4205fa593", "testCaseId": "9fb8bb79cc24c81216abb8d4205fa593", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order_without_id_order", "labels": [{"name": "story", "value": "Прием заказа"}, {"name": "suite", "value": "Прием заказа"}, {"name": "subSuite", "value": "Негативные данные"}, {"name": "feature", "value": "Заказы"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "KITCHEN"}, {"name": "thread", "value": "14296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}