{"name": "Прием заказа с верными данными", "status": "passed", "description": "Прием заказа с верными данными. Тест иногда падает, потому что Api возвращает, что нет такого заказа, хотя при проверке через получение заказа -заказ есть", "steps": [{"name": "принятие заказа ", "status": "passed", "start": 1726947209729, "stop": 1726947209849}, {"name": "Ожидаемый ответ 200, фактический 200", "status": "passed", "start": 1726947209849, "stop": 1726947209849}, {"name": "Ожидаемый json {'ok': True}, фактический {'ok': True}", "status": "passed", "start": 1726947209849, "stop": 1726947209849}], "start": 1726947209728, "stop": 1726947209850, "uuid": "dbd12abd-b8d0-4f57-96d6-d5d37b598b88", "historyId": "bbab3ca1039a92b244c55fc8f611eafc", "testCaseId": "bbab3ca1039a92b244c55fc8f611eafc", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order", "labels": [{"name": "subSuite", "value": "Позитивные данные"}, {"name": "story", "value": "Прием заказа"}, {"name": "suite", "value": "Прием заказа"}, {"name": "feature", "value": "Заказы"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "KITCHEN"}, {"name": "thread", "value": "14296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}